# Generated by Django 4.2.7 on 2023-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='article', max_length=100, verbose_name='Icon'),
        ),
    ]
